language: node_js
node_js:
  - 8

sudo: false

notifications:
  email: false

jobs:
  include:
    - stage: build
      script: npm install
      script: npm run build
      script: npm run test
    - stage: codeowners
      script: npm run update-codeowners
stages:
 - name: codeowners
   if: env(TRAVIS_EVENT_TYPE) = cron